version: '3.1'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgresUser
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: safeapp
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@safeapp.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: always

volumes:
  postgres-data:
